.SUFFIXES:
.DEFAULT_GOAL := all

ifeq ($(strip $(DEVKITPRO)),)
$(error "Please set DEVKITPRO in your environment.")
endif

ifeq ($(strip $(DEVKITPPC)),)
$(error "Please set DEVKITPPC in your environment.")
endif

include $(DEVKITPRO)/libogc2/gamecube_rules

PROJECT_DIR := $(patsubst %/,%,$(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
CARRY_ROOT ?= $(abspath $(PROJECT_DIR)/../carryhandle)

TARGET := quake2cube
BUILD  := build-gamecube

SOURCES := \
	$(PROJECT_DIR)/client \
	$(PROJECT_DIR)/qcommon \
	$(PROJECT_DIR)/server \
	$(PROJECT_DIR)/game \
	$(PROJECT_DIR)/ref_soft \
	$(PROJECT_DIR)/other \
	$(PROJECT_DIR)/null \
	$(PROJECT_DIR)/net \
	$(PROJECT_DIR)/sound \
	$(PROJECT_DIR) \

CFILES := \
	$(notdir $(wildcard $(PROJECT_DIR)/client/*.c)) \
	$(notdir $(wildcard $(PROJECT_DIR)/qcommon/*.c)) \
	$(filter-out sv_null.c,$(notdir $(wildcard $(PROJECT_DIR)/server/*.c))) \
	$(notdir $(wildcard $(PROJECT_DIR)/game/*.c)) \
	$(notdir $(wildcard $(PROJECT_DIR)/ref_soft/*.c)) \
	q_hunk.c \
	vid_menu.c \
	vid_lib.c \
	q_system.c \
	glob.c \
	cd_null.c \
	net_loopback.c \
	snddma_null.c \
	port_platform_gamecube.c \
	port_soft_gamecube.c \

CPPFILES :=
sFILES   :=
SFILES   :=

CFLAGS := \
	-g -O2 -Wall \
	-fcommon \
	-Wno-error=incompatible-pointer-types \
	-Dstricmp=strcasecmp \
	-include strings.h \
	-DSDL_MAIN_HANDLED \
	$(MACHDEP) \
	$(INCLUDE)

CXXFLAGS := $(CFLAGS)

LDFLAGS := \
	-g \
	$(MACHDEP) \
	-Wl,-Map,$(notdir $@).map

LIBS := \
	-lSDL2 \
	-lopengx \
	-laesnd \
	-logc \
	-lz \
	-lstdc++ \
	-lm

PROJECT_MAKEFILE := $(PROJECT_DIR)/Makefile.gamecube

export INCLUDE := \
	-I$(CARRY_ROOT)/include \
	-I$(PROJECT_DIR) \
	-I$(PROJECT_DIR)/$(BUILD) \
	-I$(DEVKITPRO)/libogc2/gamecube/include \
	-I$(DEVKITPRO)/libogc2/gamecube/include/SDL2 \
	-I$(DEVKITPRO)/portlibs/ppc/include \
	-I$(LIBOGC_INC)

export LIBPATHS := \
	-L$(DEVKITPRO)/libogc2/gamecube/lib \
	-L$(DEVKITPRO)/portlibs/ppc/lib \
	-L$(LIBOGC_LIB)

# Q2GC_CARRYHANDLE_MODULES
#
# Quake selects the CarryHandle modules it uses.
# CarryHandle owns their physical source directories.
#
CH_CFILES := \
	ch_dvd.c \
	ch_input.c \
	ch_input_physical.c \
	ch_pad_bus.c \
	ch_time.c \
	ch_video_gamecube.c

include $(CARRY_ROOT)/make/gamecube.mk
# ------------------------------------------------------------------
# Quake2Cube-specific disc contents.
#
# CarryHandle owns native GCM construction and Dolphin launching.
# ------------------------------------------------------------------

ifneq ($(BUILD),$(notdir $(CURDIR)))

Q2_DISC_STAGE := q2-disc-stage

.PHONY: $(Q2_DISC_STAGE)

$(Q2_DISC_STAGE):
	@test -f "$(PROJECT_DIR)/baseq2/pak0.pak" || \
		( echo "ERROR: missing baseq2/pak0.pak."; false )

	@rm -rf "$(PROJECT_DIR)/$(BUILD)/disc"
	@mkdir -p "$(PROJECT_DIR)/$(BUILD)/disc"

	@echo "Adding Quake II data"

	@cp -a \
		"$(PROJECT_DIR)/baseq2" \
		"$(PROJECT_DIR)/$(BUILD)/disc/baseq2"

endif


GCM_ROOT := \
	$(PROJECT_DIR)/$(BUILD)/disc

GCM_OUTPUT := \
	$(PROJECT_DIR)/$(TARGET).iso

GCM_TITLE := QUAKE2CUBE

GCM_REGION := PAL

GCM_PREPARE := \
	$(Q2_DISC_STAGE)


include $(CARRY_ROOT)/make/image.mk


# ------------------------------------------------------------------
# Quake2Cube test policy.
#
# Preserve the established GameCube test contract:
#
#     clean
#       -> fresh normal build
#       -> fresh ISO
#       -> Dolphin
#
# CarryHandle owns the generic Dolphin launch. TEST_TARGET keeps the
# application-specific serialized build policy in Quake2Cube.
# ------------------------------------------------------------------

ifneq ($(BUILD),$(notdir $(CURDIR)))

Q2_TEST_TARGET := q2-test-image

.PHONY: $(Q2_TEST_TARGET)

$(Q2_TEST_TARGET):
	$(MAKE) -f "$(PROJECT_MAKEFILE)" clean
	$(MAKE) -f "$(PROJECT_MAKEFILE)"
	$(MAKE) -f "$(PROJECT_MAKEFILE)" iso

TEST_TARGET := $(Q2_TEST_TARGET)

endif


include $(CARRY_ROOT)/make/dolphin.mk
